consump <- read.table("C:/Users/trant/Downloads/STUDY/COURSERA/Exploring data/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subconsump <- consump[consump$Date %in% c("1/2/2007","2/2/2007") ,]
date <- strptime(paste0(subconsump$Date, subconsump$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
globalActivePower <- as.numeric(subconsump$Global_active_power)
globalReactivePower <- as.numeric(subconsump$Global_reactive_power)
metering1 <- as.numeric(subconsump$Sub_metering_1)
metering2 <- as.numeric(subconsump$Sub_metering_2)
metering3 <- as.numeric(subconsump$Sub_metering_3)
voltage <- as.numeric(subconsump$Voltage)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
plot(date, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(date, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(date, metering1, type="l", ylab="Energy sub metering", xlab="")
lines(date, metering2, type="l", col="red")
lines(date, metering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2, col=c("black", "red", "blue"), bty="o")
plot(date, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
savehistory("C:/Users/trant/Downloads/STUDY/COURSERA/Exploring data/ExData_Plotting1/plot4.R")
