library(swirl)
swirl
swirl()
head(airquality)
range(airquality$Ozone, na.rm = TRUE)
hist(airquality$Ozone)
table(airquality$Month)
boxplot(Ozone~Month,  airquality)
boxplot(Ozone~Month,  airquality, xlab = "Month", xlab = "Ozone (ppb)", col.axis = "blue", col.lab = "red")
boxplot(Ozone~Month,  airquality, xlab = "Month", xlab = "Ozone (ppb)")
boxplot(Ozone~Month,  airquality, xlab = "Month", ylab = "Ozone (ppb)", col.axis = "blue", col.lab = "red")
boxplot(Ozone~Month,  airquality, xlab = "Month", ylab = "Ozone (ppb)", col.axis = "blue", col.lab = "red", main = "Ozone and Wind in New York City")
title(main="Ozone and Wind in New York City")
plot(airquality, plot)
skip()
title(main = "Ozone and Wind in New York City")
par(50)
length(par())
names(par())
par()$pin
par()$fg
par("pch")
par("lty")
plot(airquality$Wind, airquality$Ozone, type = "n")
title("Wind and Ozone in NYC")
may <- airquality$Month
may <- subset(airquality, Month==5)
points(wind, ozone)
points(airquality$wind, airquality$ozone)
points(may$Wind,may$Ozone,col="blue",pch=17)
notmay <- subset(airquality, !Month==5)
notmay <- subset(airquality, Month!==5)
notmay <- subset(airquality, Month!=5)
points(notmay$Wind, notmay$Ozone)
points(notmay$Wind,notmay$Ozone,col="red",pch=8)
legend("topright", pch = c(17,8), col = c("blue","red"), legend = c("May","Other Months"))
line(median(airquality$Wind, lty=2, with(2)))
skip
abline(v=median(airquality$Wind),lty=2,lwd=2)
par(mfrow = c(1,2))
title("Ozone and Wind")
plot(airquality$Wind, airquality$Ozone, main = "Ozone and Wind")
title(main = "Ozone and Solar Radiation")
plot(airquality$Ozone, airquality$Solar.R, main = "Ozone and Solar Radiation")
par(mfrow = c(1, 3), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
plot(airquality$Wind, airquality$Ozone, main = "Ozone and Wind")
plot(airquality$Solar.R, airquality$Ozone, main = "Ozone and Solar Radiation")
plot(airquality$Temp, airquality$Ozone, main = "Ozone and Temperature")
mtext("Ozone and Weather in New York City" = TRUE)
mtext("Ozone and Weather in New York City" == TRUE)
mtext("Ozone and Weather in New York City" == TRUE)
mtext("Ozone and Weather in New York City", outer = TRUE)
swirl()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
skip()
swirl()
getwd()
setwd("C:/Users/trant/Downloads/STUDY/COURSERA/Exploring data/ExData_Plotting1")
consump <- read.table("C:/Users/trant/Downloads/STUDY/COURSERA/Exploring data/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subconsump <- consump[consump$Date %in% c("1/2/2007","2/2/2007") ,]
date <- strptime(paste0(subconsump$Date, subconsump$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
globalActivePower <- as.numeric(subconsump$Global_active_power)
png("plot2.png", width=480, height=480)
plot(date, globalActivePower, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
savehistory("C:/Users/trant/Downloads/STUDY/COURSERA/Exploring data/ExData_Plotting1/plot2.R")
